/* DASH booking submission client. */
(function(){
'use strict';
const ENDPOINT='https://roywoofgypiyoobdcrwx.supabase.co/functions/v1/create-service-request';
const $=id=>document.getElementById(id); const val=id=>$(id)?String($(id).value||'').trim():'';
const lawnServices=[['lawn-mowing','Lawn Mowing','Routine mowing to keep your grass neat, manageable, and well maintained.'],['weed-removal','Weed Removal','Keep your outdoor spaces looking clean and maintained.'],['mulch-installation','Mulch Installation','Installation and spreading of mulch in existing landscape beds and suitable outdoor areas.'],['decorative-rock','Decorative Rock Installation','Enhance the appearance of your outdoor space with decorative rock.'],['yard-cleanup','Yard Cleanup','Restore a clean, organized appearance to your outdoor space.'],['trimming-edging','Trimming & Edging','Keep lawn and landscape areas clean and well defined.'],['seasonal-yard-cleanup','Seasonal Yard Cleanup','Prepare your property for the changing seasons.'],['property-maintenance','Property Maintenance','Keep your outdoor property clean, organized, and maintained.']];
function isLawn(){return lawnServices.some(s=>s[0]===val('service'));}
function setLawnMode(on){['year','make','model','engine','trim'].forEach(id=>{const e=$(id);const f=e?.closest('.field');if(f)f.classList.toggle('dash-lawn-hidden',on);});}
function openLawnBooking(key){const cat=$('lawn-property-booking');if(cat)cat.classList.add('open');const list=cat?.querySelector('.lawn-service-list');if(list)list.hidden=false;const automotive=$('automotive');if(automotive)automotive.classList.remove('open');const booking=$('booking');if(!booking)return;booking.classList.add('open');$('service').value=key;setLawnMode(true);$('estimate')?.classList.remove('open');$('review')?.classList.remove('open');$('contact')?.classList.remove('open');document.getElementById('p1')?.classList.remove('active');document.getElementById('p2')?.classList.add('active');booking.scrollIntoView({behavior:'smooth'});}
function addLawnServices(){if($('lawn-property-booking'))return;const lawn=document.createElement('section');lawn.className='category';lawn.id='lawn-property-booking';lawn.innerHTML='<button type="button" class="category-head lawn-toggle" aria-expanded="false"><h2>Lawn & Property Care</h2><p>Mobile lawn and property-care services currently available for booking.</p></button><div class="services lawn-service-list" hidden>'+lawnServices.map(s=>`<div class="service"><strong>${s[1]}</strong><span>${s[2]}</span><button type="button" data-lawn="${s[0]}">Continue</button></div>`).join('')+'</div>';
const automotive=document.getElementById('automotive');
if(automotive&&automotive.parentNode) automotive.parentNode.insertBefore(lawn,automotive.nextSibling); else {const container=document.querySelector('main')||document.body;container.appendChild(lawn);}
const toggle=lawn.querySelector('.lawn-toggle'),list=lawn.querySelector('.lawn-service-list');toggle.addEventListener('click',()=>{const open=!lawn.classList.contains('open');lawn.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));list.hidden=!open;});lawn.querySelectorAll('[data-lawn]').forEach(b=>b.addEventListener('click',()=>openLawnBooking(b.dataset.lawn)));
const style=document.createElement('style');style.textContent='#lawn-property-booking{display:block!important;background:#fff;border:1px solid #e2e8f0;border-radius:16px;overflow:hidden;margin-bottom:28px;box-shadow:0 8px 25px rgba(15,23,42,.05)}#lawn-property-booking .lawn-toggle{width:100%;border:0;background:#fff;text-align:left;padding:28px;cursor:pointer;color:#111827;font:inherit}#lawn-property-booking .lawn-toggle h2{font-size:30px;margin-bottom:6px}#lawn-property-booking .lawn-toggle p{color:#475569;margin:0}.dash-lawn-hidden{display:none!important}#lawn-property-booking .lawn-service-list[hidden]{display:none!important}#lawn-property-booking .lawn-service-list{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;padding:18px 24px 24px;border-top:1px solid #e2e8f0}@media(max-width:650px){#lawn-property-booking .lawn-service-list{grid-template-columns:1fr}#lawn-property-booking .lawn-toggle{padding:22px}#lawn-property-booking .lawn-toggle h2{font-size:26px}}';document.head.appendChild(style);
const originalOpen=window.openBooking;window.openBooking=function(s){if(lawnServices.some(x=>x[0]===s))openLawnBooking(s);else{setLawnMode(false);originalOpen?.(s);}};
const originalCalc=window.calculateEstimate;window.calculateEstimate=function(){if(!isLawn()){setLawnMode(false);return originalCalc?.();}setLawnMode(true);$('laborPrice').textContent='Estimate required';$('partsPrice').textContent='To be determined';$('totalPrice').textContent='Pending';$('estimate')?.classList.add('open');$('review')?.classList.remove('open');$('contact')?.classList.remove('open');};
const originalReview=window.reviewBooking;window.reviewBooking=function(){if(!isLawn()){setLawnMode(false);return originalReview?.();}if(!val('date')||!val('time')){alert('Please enter your preferred service date and arrival time.');return;}const grid=$('reviewGrid');if(!grid)return;grid.innerHTML=`<div><strong>Service</strong>${$('service').options[$('service').selectedIndex]?.text||''}</div><div><strong>Preferred Date</strong>${val('date')}</div><div><strong>Preferred Time</strong>${val('time')}</div><div class="full"><strong>Service Address</strong>${typeof fullAddress==='function'?fullAddress():[val('locationStreet'),val('locationCity'),val('locationState'),val('locationZip')].filter(Boolean).join(', ')}</div><div class="full"><strong>Notes</strong>${val('notes')||'None'}</div>`;$('estimate')?.classList.remove('open');$('review')?.classList.add('open');};}
async function sendBooking(){/* existing submission is retained by the page's original handler */}
function install(){addLawnServices();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
