/* DASH MOBILE SERVICES internal pricing engine. Customer sees only the final estimate. */
(function(){
'use strict';
const CONFIG={ownerHourly:30,employeeHourly:10,employerBurdenRate:.15,fuelCostPerMile:.70,equipmentOverheadPerLaborHour:4,businessOverheadPerJob:3,targetProfitMargin:.25,includedOilQuarts:5,extraOilPerQuart:8,salesTaxRate:0,travelBaseMiles:10,travelIncludedFee:10,travelPerMileAfterBase:.75};
const AUTOMOTIVE={oil:{labor:30,parts:32,minutes:45,startingAt:75.99},wipers:{labor:20,parts:35,minutes:20,startingAt:69.99},battery:{labor:35,parts:160,minutes:35,startingAt:239.99},jump:{labor:35,parts:0,minutes:20,startingAt:29.99},tire:{labor:25,parts:0,minutes:20,startingAt:29.99},'tire-replacement':{labor:35,parts:125,minutes:45,startingAt:199.99},air:{labor:25,parts:35,minutes:25,startingAt:72.99},cabin:{labor:25,parts:35,minutes:25,startingAt:72.99},headlight:{labor:65,parts:150,minutes:60,startingAt:239.99},'brake-light':{labor:45,parts:80,minutes:40,startingAt:139.99},fluid:{labor:25,parts:15,minutes:20,startingAt:44.99}};
const LAWN={'lawn-mowing':{labor:45,minutes:60,materials:2,startingAt:44.99},'weed-removal':{labor:50,minutes:60,materials:3,startingAt:44.99},'mulch-installation':{labor:55,minutes:60,materials:55,startingAt:119.99},'decorative-rock':{labor:60,minutes:60,materials:65,startingAt:129.99},'yard-cleanup':{labor:75,minutes:90,materials:5,startingAt:59.99},'trimming-edging':{labor:35,minutes:45,materials:1,startingAt:39.99},'seasonal-yard-cleanup':{labor:150,minutes:180,materials:8,startingAt:99.99},'property-maintenance':{labor:60,minutes:60,materials:3,startingAt:44.99}};
const $=id=>document.getElementById(id),val=id=>$(id)?String($(id).value||'').trim():'';
function isLawn(s){return !!LAWN[s]}
function choices(){return [...document.querySelectorAll('input[name="specialChoice"]:checked')].map(x=>x.value)}
function travelCost(){return CONFIG.travelIncludedFee}
function internalCost(service,mode,parts,minutes){const hours=Math.max(minutes/60,.25);const wage=mode==='employee'?CONFIG.employeeHourly*(1+CONFIG.employerBurdenRate):CONFIG.ownerHourly;return wage*hours+parts+CONFIG.equipmentOverheadPerLaborHour*hours+CONFIG.businessOverheadPerJob+travelCost()}
function priceFromCost(cost){return Math.max(cost+10,cost/(1-CONFIG.targetProfitMargin))}
function automotiveEstimate(s){let base=AUTOMOTIVE[s]||{labor:30,parts:0,minutes:30,startingAt:39.99},labor=base.labor,parts=base.parts,minutes=base.minutes;const c=choices();if(s==='wipers'){const n=c.includes('All wipers')?4:Math.max(c.length,1);labor=20*n;parts=35*n;minutes=20*n}if(s==='tire-replacement'){const n=parseInt(c[0]||'1',10);labor=35*n;parts=125*n;minutes=45*n}if(s==='headlight'||s==='brake-light'){const n=(c[0]==='Both'||c[0]==='Two')?2:1;labor=base.labor*n;parts=base.parts*n;minutes=base.minutes*n}if(s==='fluid'){parts=15*Math.max(c.length,1)}const cost=internalCost(s,'employee',parts,minutes),calculated=priceFromCost(cost);const baseCost=priceFromCost(internalCost(s,'employee',base.parts,base.minutes));const multiplier=calculated>baseCost?calculated/baseCost:1;const total=Math.max(base.startingAt,calculated*multiplier);return {labor,parts,total,startingAt:base.startingAt,minutes,cost,profit:total-cost}}
function lawnEstimate(s){const b=LAWN[s];if(!b)return null;const cost=internalCost(s,'employee',b.materials,b.minutes),total=Math.max(b.startingAt,priceFromCost(cost));const labor=Math.max(b.labor,total-b.materials-travelCost());return {labor,parts:b.materials,total,startingAt:b.startingAt,minutes:b.minutes,cost,profit:total-cost}}
function addStartingAt(){document.querySelectorAll('#services .service').forEach(card=>{const button=card.querySelector('button');if(!button)return;const m=(button.getAttribute('onclick')||'').match(/openBooking\(['"]([^'"]+)/);if(!m)return;const e=AUTOMOTIVE[m[1]];if(!e)return;if(!card.querySelector('.starting-at')){const p=document.createElement('span');p.className='starting-at';p.style='display:block;font-size:13px;font-weight:800;color:#111827;margin-top:6px';p.textContent='Starting at $'+e.startingAt.toFixed(2);button.parentNode.insertBefore(p,button)}})}
function override(){const old=window.calculateEstimate;window.calculateEstimate=function(){const s=val('service');if(!s){alert('Please select a service first.');return}const e=isLawn(s)?lawnEstimate(s):automotiveEstimate(s);if(!e){if(old)return old();return}if($('laborPrice'))$('laborPrice').textContent='$'+e.labor.toFixed(2);if($('partsPrice'))$('partsPrice').textContent='$'+e.parts.toFixed(2);if($('totalPrice'))$('totalPrice').textContent='$'+e.total.toFixed(2);const estimate=$('estimate');if(estimate){let badge=$('startingAtPrice');if(!badge){badge=document.createElement('div');badge.id='startingAtPrice';badge.style='font-size:13px;color:#475569;margin:-4px 0 12px;font-weight:700';const h=estimate.querySelector('h2');if(h)h.insertAdjacentElement('afterend',badge)}badge.textContent='Starting at $'+e.startingAt.toFixed(2)+' • Final estimate based on your selections';estimate.classList.add('open')}if(typeof setStep==='function')setStep(3);estimate?.scrollIntoView({behavior:'smooth'})};window.DASH_PRICING={CONFIG,AUTOMOTIVE,LAWN,estimate:s=>isLawn(s)?lawnEstimate(s):automotiveEstimate(s)};addStartingAt()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',override);else override();
})();
