(()=>{
const URL='https://roywoofgypiyoobdcrwx.supabase.co';
const KEY='sb_publishable_5SKEbO1wFS4LVZ6IcpWfnA_UQffaKX_';
const API=URL+'/functions/v1/employee-management';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[];
function token(){for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(!k.includes('auth-token'))continue;try{const v=JSON.parse(localStorage.getItem(k)||'null');const t=v?.access_token||v?.currentSession?.access_token||v?.session?.access_token;if(t)return t}catch{}}return null}
async function api(action,p={}){const t=token();if(!t)throw Error('No active Supabase login session. Sign in again.');const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),10000);try{const r=await fetch(API,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+t,'Content-Type':'application/json'},cache:'no-store',signal:ctl.signal,body:JSON.stringify({action,...p})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||('Request failed ('+r.status+')'));return j.data}finally{clearTimeout(timer)}}
async function load(){const h=document.querySelector('#employees .body');if(!h)return;h.innerHTML='<div class="empty"><strong>Loading employee records...</strong></div>';try{const data=await api('list');rows=Array.isArray(data)?data:[];render()}catch(e){h.innerHTML='<div class="empty"><strong>Unable to load employee records</strong><p>'+esc(e.name==='AbortError'?'Request timed out. Click Refresh to try again.':e.message)+'</p><button class="btn" id="empRetry">Try Again</button></div>';h.querySelector('#empRetry').onclick=load}}
function render(){const h=document.querySelector('#employees .body');const active=rows.filter(e=>String(e.employment_status||'active').toLowerCase()==='active');const inactive=rows.filter(e=>String(e.employment_status||'').toLowerCase()!=='active');const block=(list,off)=>list.length?list.map(e=>{const n=[e.first_name,e.last_name].filter(Boolean).join(' ')||'Unnamed';const p=e.hourly_pay_rate==null?'—':'$'+Number(e.hourly_pay_rate).toFixed(2)+'/hr';return '<div class="row"><div><strong>'+esc(n)+'</strong><span class="mini">ID: '+esc(e.employee_id)+' · '+esc(e.position||'—')+' · '+esc(e.role||'—')+'</span><span class="mini">Phone: '+esc(e.phone||'—')+' · Email: '+esc(e.email||'—')+' · Pay: '+esc(p)+'</span></div><div class="toolbar"><button class="btn light" data-edit="'+esc(e.employee_id)+'">Edit</button><button class="btn light" data-pay="'+esc(e.employee_id)+'">Edit Pay</button><button class="btn light" data-remove="'+esc(e.employee_id)+'">Remove</button>'+ (off?'<button class="btn light" data-restore="'+esc(e.employee_id)+'">Restore</button>':'') +'<span class="pill">'+esc(e.employment_status||'active')+'</span></div></div>'}).join(''):'<div class="empty"><strong>No '+(off?'removed/inactive':'active')+' employees</strong></div>';h.innerHTML='<div class="toolbar" style="margin-bottom:15px"><button class="btn" id="empAdd">+ Add Employee</button><button class="btn light" id="empRefresh">Refresh</button><button class="btn light" id="empSupabase">Open Supabase Employee Records</button></div><div class="panel"><div class="head"><h2>Active Employees</h2></div><div class="body">'+block(active,false)+'</div></div><div class="panel"><div class="head"><h2>Removed / Inactive Employees</h2></div><div class="body">'+block(inactive,true)+'</div></div>';h.querySelector('#empAdd').onclick=add;h.querySelector('#empRefresh').onclick=load;h.querySelector('#empSupabase').onclick=()=>window.open('https://supabase.com/dashboard/project/roywoofgypiyoobdcrwx/editor','_blank');h.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));h.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>pay(b.dataset.pay));h.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>remove(b.dataset.remove));h.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>restore(b.dataset.restore))}
async function add(){const id=prompt('Employee ID:');if(!id)return;const first=prompt('First name:');if(!first)return;try{await api('add',{employee_id:id,first_name:first,last_name:prompt('Last name:')||null,email:prompt('Email:')||null,phone:prompt('Phone:')||null,position:prompt('Position:')||null,role:prompt('Role:','employee')||'employee',employment_status:'active',hourly_pay_rate:null,hire_date:null,notes:null});await load()}catch(e){alert(e.message)}}
async function edit(id){const e=rows.find(x=>String(x.employee_id)===String(id));if(!e)return;try{await api('update',{employee_id:e.employee_id,first_name:prompt('First name:',e.first_name||'')||e.first_name,last_name:prompt('Last name:',e.last_name||'')||null,email:prompt('Email:',e.email||'')||null,phone:prompt('Phone:',e.phone||'')||null,position:prompt('Position:',e.position||'')||null,role:prompt('Role:',e.role||'employee')||'employee',employment_status:prompt('Status:',e.employment_status||'active')||'active',hire_date:e.hire_date||null,notes:e.notes||null});await load()}catch(x){alert(x.message)}}
async function pay(id){const e=rows.find(x=>String(x.employee_id)===String(id));const v=prompt('Hourly pay rate:',e?.hourly_pay_rate??'');if(v===null)return;const rate=Number(v);if(!Number.isFinite(rate)||rate<0){alert('Enter a valid non-negative pay rate.');return}try{await api('pay',{employee_id:id,hourly_pay_rate:rate});await load()}catch(x){alert(x.message)}}
async function remove(id){if(!confirm('Remove this employee?'))return;try{await api('remove',{employee_id:id});await load()}catch(x){alert(x.message)}}
async function restore(id){try{await api('restore',{employee_id:id});await load()}catch(x){alert(x.message)}}
window.loadAdminEmployees=load;
const nav=[...document.querySelectorAll('aside button')].find(b=>b.textContent.trim()==='Employee Records');if(nav)nav.onclick=()=>{show('employees',nav);load()};
load();
})();